- name: Update a10_slb_template_logging example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_logging instance
    a10_slb_template_logging:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      state: present
      name: my_logging
