- name: Delete a10_slb_template_tcp example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_tcp instance
    a10_slb_template_tcp:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: my_tcp



















