- name: Create bgp example playbook
  connection: local
  hosts: "{{desired_inventory_group}}"
  tasks:
  - name: Create router bgp for acos
    a10.acos_axapi.a10_router_bgp:
      as_number: 106
