---
- debug: msg="Start START a10_cgnv6_lsn_rule_list_domain_name"
- name: Create a10_cgnv6_lsn_rule_list_domain_name instance
  a10_cgnv6_lsn_rule_list_domain_name:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: "RULE1"
      name_domain: "www.cnn.com"
      rule_cfg:
          - proto: "tcp"
            tcp-cfg: {
                    "start-port": 0,
                    "action-type": "pass-through",
                    "action-cfg": "action"
                }
          - proto: "icmp"
            icmp-others-cfg: {
                    "action-cfg": "action",
                    "action-type": "drop"
           }
          - proto: "udp"
            udp-cfg: {
                   "action-cfg": "no-action",
                   "start-port": 0
            }
- debug: msg="Stop a10_cgnv6_lsn_rule_list_domain_name"

