---
- debug: msg="Start START a10_cgnv6_lsn_lid"
- name: Create a10_cgnv6_lsn_lid instance
  a10_cgnv6_lsn_lid:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      lid_number: 2
      state: present
      lsn_rule_list: {
        "destination":"RULE1"
      }
      source_nat_pool:
            "pool-name": 
               "{{ NAT1_POOL_NAME }}"
      user_quota: {
          "quota-udp": {
            "udp-quota":500
          },
          "quota-tcp": {
            "tcp-quota":500,
            "tcp-reserve":10
          }
          }
- debug: msg="Stop START a10_cgnv6_lsn_lid"
