---
- debug: msg="START a10_cgnv6_nat_pool"
- name: Create a10_cgnv6_nat_pool
  a10_cgnv6_nat_pool:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      pool_name: "{{ NAT1_POOL_NAME }}"
      start_address: "{{ NAT1_START_ADDRESS }}"
      end_address: "{{ NAT1_END_ADDRESS }}"
      netmask: "{{ NAT1_POOL__MASK }}"
      max_users_per_ip: 128
      port_batch_v2_size: 256
      simultaneous_batch_allocation: 1

- debug: msg="STOP a10_cgnv6_nat_pool"

