---
- debug: msg="START a10_cgnv6_server"
- name: Create a10_cgnv6_server
  a10_cgnv6_server:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      name: "SERVER-ANSIBLE"
      host: "20.17.53.199"
      port_list: [
        {
          "port-number":514,
          "protocol":"udp",
          "health-check-disable":1,
        }
      ]
      health_check_disable: 1
- debug: msg="STOP a10_cgnv6_server"

- debug: msg="START a10_cgnv6_service_group"
- name: Create a10_cgnv6_service_group
  a10_cgnv6_service_group:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      name: "SG-ANSIBLE"
      protocol: "udp"
      member_list: [
          {
            "name":"SERVER-ANSIBLE",
            "port":514
          }
        ]
- debug: msg="STOP a10_cgnv6_service_group"

- debug: msg="START a10_cgnv6_template_logging"
- name: Create a10_cgnv6_template_logging
  a10_cgnv6_template_logging:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      name: "LOG-ANSIBLE"
      format: "compact"
      service_group: "SG-ANSIBLE"
      facility: "local5"
      include_destination: 1
      batched_logging_disable: 0
      disable_log_by_destination: {
        "udp-list": [
          {
            "udp-port-start":53,
            "udp-port-end":53
          }
        ],
        "icmp":1
      }
      log: {
            "port-overloading": 0,
            "sessions": 1
        }

- debug: msg="STOP a10_cgnv6_template_logging"

- debug: msg="START a10_cgnv6_template_default_logging"
- name: Create a10_cgnv6_template_default_logging
  a10_cgnv6_template_default_logging:
      a10_host: "{{ inventory_hostname }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      logging: { "default-template":"LOG-ANSIBLE" }
- debug: msg="STOP a10_cgnv6_template_default_logging"

#- debug: msg="START sh ver"
#- name: show version
#  ios_command:
#      commands:
#        - show version
#      username: "{{ a10_username }}"
#      password: "{{ a10_password }}"
#      host: "{{ inventory_hostname }}"
#  register: output
#
#- assert:
#      that:
#        - "'4.1.2-P2' in output['stdout'][0]"
#- debug: var=output
#- debug: msg="STOP sh ver"
#
