---
# Configure interface
- debug: msg="START a10_interface.yaml"
- name: Create an interface configuration
  a10_interface_ethernet:
        a10_host: "{{ inventory_hostname }}"
        a10_username: "{{ a10_username }}"
        a10_password: "{{ a10_password }}"
        a10_port: 80
        a10_protocol: http
        state: present
        ifnum: 2
        name: "Outside Created by Ansible"
        action: "enable"
        ip: {
            "dhcp":1,
            "inside":0,
            "outside":1,
            }
- debug: msg="STOP a10_interface.yaml"

- debug: msg="START a10_interface.yaml"
- name: Create an interface configuration
  a10_interface_ethernet:
        a10_host: "{{ inventory_hostname }}"
        a10_username: "{{ a10_username }}"
        a10_password: "{{ a10_password }}"
        a10_port: 80
        a10_protocol: http
        state: present
        ifnum: 1
        name: "Inside Created by Ansible"
        action: "enable"
        ip: {
            "dhcp":1,
            "inside":1,
            "outside":0,
            }
- debug: msg="STOP a10_interface.yaml"

