---
# Configure interface 
- debug: msg="START a10_interface.yaml"
- name: Create an interface configuration
  a10_interface_ethernet:
        a10_host: "{{ inventory_hostname }}"
        a10_username: admin
        a10_password: a10
        state: present
        ifnum: 1
        ip: { 
            "inside":1,
            "outside":0,
            "name": "Inside Created by Ansible"
            }
- debug: msg="STOP a10_interface.yaml"
