- name: Create a10_slb_template_imap_pop3 example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_imap_pop3 instance
    a10_slb_template_imap_pop3:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      name: my_imap-pop3
