- name: Delete a10_interface_tunnel example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_interface_tunnel instance
    a10_interface_tunnel:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent




      ifnum: 1






