authors:
- opensource@a10networks.com
description: Collection of modules used to configure ACOS devices over AXAPIs
documentation: https://github.com/a10networks/a10-acos-axapi/blob/master/README.md
license:
- GPL-2.0-or-later
name: acos_axapi
namespace: a10
readme: README.md
repository: https://github.com/a10networks/a10-acos-axapi
tags:
- acos
version: 6.0.5-91924
