
- name: Create a10_cgnv6_nat_inside_source_static example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_nat_inside_source_static instance
    a10_cgnv6_nat_inside_source_static:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      src_address: 10.0.0.1
      partition: NO_EXAMPLE
