- name: Save Configuration (Write Memory) example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: a10_write_memory instance
    a10_write_memory:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}}"
      partition: "shared"
      destination: "primary"

