
- name: Update a10_slb_template_diameter example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_diameter instance
    a10_slb_template_diameter:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: present
      name: my_diameter
