- name: Update a10_slb_virtual_server_port example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_virtual_server_port instance
    a10_slb_virtual_server_port:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      state: present
      port_number: 8080
      protocol: tcp
      conn_limit: 1
      action: enable
      def_selection_if_pref_failed: def-selection-if-pref-failed
      stats_data_action: stats-data-enable
      scaleout_bucket_count: 1
      template_tcp: default
      template_virtual_port: default
      virtual_server_name: "vserver1"
