---
- debug: msg="Start START a10_cgnv6_lsn_lid"
- name: Create a10_cgnv6_lsn_lid instance
  a10_cgnv6_lsn_lid:
      a10_host: "{{ inventory_hostname }}"
      a10_username: admin
      a10_password: a10
      lid_number: 2
      state: present
      source_nat_pool:
            "pool-name": 
               "{{ NAT3_POOL_NAME }}"
      user_quota: {
          "quota-udp": {
            "udp-quota":200
          },
          "quota-tcp": {
            "tcp-quota":100,
            "tcp-reserve":10
          }
          }
- debug: msg="Stop START a10_cgnv6_lsn_lid"
