- name: Update a10_slb_template_persist_cookie example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_persist_cookie instance
    a10_slb_template_persist_cookie:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      state: present
      name: my_cookie
      encrypt_level: 0
      pass_phrase: ACOS4KEY
      cookie_name: sto-id
      path: /
