- name: Create a10_slb_template_monitor example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_monitor instance
    a10_slb_template_monitor:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      id: 1
      monitor_relation: monitor-and
