- name: Update a10_slb_template_diameter example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_diameter instance
    a10_slb_template_diameter:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      state: present
      name: my_diameter
      dwr_time: 0
      idle_timeout: 1
      session_age: 1
      dwr_up_retry: 1
