- name: Update a10_slb_template_respmod_icap example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Update a10_slb_template_respmod_icap instance
    a10_slb_template_respmod_icap:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      state: absent
      name: my_respmod-icap
      preview: 1
