- name: Delete a10_slb_virtual_server example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_virtual_server instance
    a10_slb_virtual_server:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: vs1


      ip_address: 192.168.42.1

      netmask: 255.255.255.0






















      port_list: [{'protocol': 'https', 'port-number': 443}, {'protocol': 'http', 'port-number': 80, 'template-persist-cookie': 'sg-cookie-persist'}, {'protocol': 'tcp', 'port-number': 22}]

