- name: Delete a10_cgnv6_ddos_protection example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_cgnv6_ddos_protection instance
    a10_cgnv6_ddos_protection:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent







