
- name: Create a10_slb_template_port example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_slb_template_port instance
    a10_slb_template_port:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      name: my_port
