- name: Delete a10_slb_template_server_ssl example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Delete a10_slb_template_server_ssl instance
    a10_slb_template_server_ssl:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      state: absent
      name: my_server-ssl





























