- name: Create gslb_policy example playbook
  connection: local
  hosts: "{{desired_inventory_group}}"
  tasks:
  - name: Create a10.acos_axapi.a10_gslb_policy instance
    a10.acos_axapi.a10_gslb_policy:
      name: mydomain-policy
      dns: 
        selected_only: true
        selected_only_value: 1
        server: true
        server_authoritative: 1