- name: Update gslb protocol example playbook
  connection: local
  hosts: "{{desired_inventory_group}}"
  tasks:
  - name: Update a10.acos_axapi.a10_gslb_protocol instance
    a10.acos_axapi.a10_gslb_protocol:
      state: present
      enable_list:
        - ntype: controller
        - ntype: device