- name: Create a10_glm_enterprise_ha_host example playbook
  connection: local
  hosts: "{{desired_inventory_group}}"
  tasks:
  - name: Create a10.acos_axapi.a10_glm_enterprise_ha_host instance
    a10.acos_axapi.a10_glm_enterprise_ha_host:
      host_entry: 10.10.10.10