- name: Change Admin Password example playbook
  connection: local
  hosts: "{{desired_inventory_group}}"
  tasks:
  - name: Change password a10.acos_axapi.a10_admin_password instance
    a10.acos_axapi.a10_admin_password:
      admin_user: admin
      password_in_module : password@a10

