- name: a10_cgnv6_stateful_firewall_tcp_idle_timeout example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_stateful_firewall_tcp_idle_timeout
    a10_cgnv6_stateful_firewall_tcp_idle_timeout:
      a10_host: "10.43.12.137"
      a10_username: "admin"
      a10_password: "a10"
      a10_port: "443"
      a10_protocol: "https"
      partition: "MyPartition"
      port_end: "9000"
      idle_timeout_val_port_range: "500"
      port: "8000"
