
- name: Create a10_cgnv6_nat46_stateless_fragmentation_inbound example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: Create a10_cgnv6_nat46_stateless_fragmentation_inbound instance
    a10_cgnv6_nat46_stateless_fragmentation_inbound:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
