- name: Assign interface IP address
  connection: local
  hosts: localhost
  tasks:
  - name: Assign interface IP address
    a10_interface_ethernet:
      state: "{{ state }}"
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
      ip:
        address_list:
        -  ipv4-address: "{{ 10.0.0.4 }}"
           ipv4-netmask: "{{ 255.255.255.0 }}"
      ifnum: 1
      action: enable
