- name: A10 import aflex example 
  connection: local
  hosts: localhost
  tasks:
  - name: Import aflex files 
    a10_import:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_protocol: "{{ a10_protocol }}"
      a10_port: "{{ a10_port }}"
      aflex: "aflex_script_name"
      remote_file: "scp://username:password@host:/path/to/file"
