- name: a10_cgnv6_sctp_global example playbook
  connection: local
  hosts: localhost
  tasks:
  - name: a10_cgnv6_sctp_global
    a10_cgnv6_sctp_global:
      a10_host: "{{ a10_host }}"
      a10_username: "{{ a10_username }}"
      a10_password: "{{ a10_password }}"
      a10_port: "{{ a10_port }}"
      a10_protocol: "{{ a10_protocol }}"
